---
version: '3'
services:
  java:
    image: sahith1208/nitjava:v1
    ports:
      - "8000:80"
    deploy:
      replicas: 3
  devops:
    image: sahith1208/nitdevops:v1
    ports:
      - "8001:80"
    deploy:
      replicas: 3
  datascience:
    image: sahith1208/nitdatascience:v1
    ports:
      - "8002:80"
    deploy:
      replicas: 3
